<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">

	<title>Cluster - Creative Portfolio HTML Template</title>
 
	<!-- Main CSS file -->
	<link rel="stylesheet" href="/apps/frontend/public/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/apps/frontend/public/css/owl.carousel.css" />
	<link rel="stylesheet" href="/apps/frontend/public/css/magnific-popup.css" />
	<link rel="stylesheet" href="/apps/frontend/public/css/font-awesome.css" />
	<link rel="stylesheet" href="/apps/frontend/public/css/style.css" />
	<link rel="stylesheet" href="/apps/frontend/public/css/responsive.css" />


	<!-- Favicon -->
	<link rel="shortcut icon" href="/apps/frontend/public/images/icon/favicon.png">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apps/frontend/public/images/icon/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apps/frontend/public/images/icon/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apps/frontend/public/images/icon/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/apps/frontend/public/images/icon/apple-touch-icon-57-precomposed.png">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>

<!-- PRELOADER -->
<div id="st-preloader">
	<div id="pre-status">
		<div class="preload-placeholder"></div>
	</div>
</div>
<!-- /PRELOADER -->


<!-- HEADER -->
<header id="header">
	<nav class="navbar st-navbar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#st-navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="logo" href="index.html"><img src="/apps/frontend/public/images/logo.png" alt=""></a>
			</div>

			<div class="collapse navbar-collapse" id="st-navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<?php foreach ($menu as $m):?>
					<li><a href="<?=$m->url?>"><?=$m->title?></a></li>
						<?php endforeach;?>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container -->
	</nav>
</header>
<!-- /HEADER -->


<!-- SLIDER -->
<?php echo $this->getContent();?>
<!-- Scroll-up -->
<div class="scroll-up">
	<ul><li><a href="#header"><i class="fa fa-angle-up"></i></a></li></ul>
</div>


<!-- JS -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.min.js"></script><!-- jQuery -->
<script type="text/javascript" src="/apps/frontend/public/js/bootstrap.min.js"></script><!-- Bootstrap -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.parallax.js"></script><!-- Parallax -->
<script type="text/javascript" src="/apps/frontend/public/js/smoothscroll.js"></script><!-- Smooth Scroll -->
<script type="text/javascript" src="/apps/frontend/public/js/masonry.pkgd.min.js"></script><!-- masonry -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.fitvids.js"></script><!-- fitvids -->
<script type="text/javascript" src="/apps/frontend/public/js/owl.carousel.min.js"></script><!-- Owl-Carousel -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.counterup.min.js"></script><!-- CounterUp -->
<script type="text/javascript" src="/apps/frontend/public/js/waypoints.min.js"></script><!-- CounterUp -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.isotope.min.js"></script><!-- isotope -->
<script type="text/javascript" src="/apps/frontend/public/js/jquery.magnific-popup.min.js"></script><!-- magnific-popup -->
<script type="text/javascript" src="/apps/frontend/public/js/scripts.js"></script><!-- Scripts -->


</body>
</html>